spring:
  profiles:
    active: local
  datasource:
    url: ${clearDB}
    username: ${clearDB_USER}
    password: ${clearDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
#        format_sql: true
#        use_sql_comments: true

  jwt:
    secret: pepega524832857240

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #logging.level:
#  org.hibernate.SQL: debug
  # org.hibernate.type: trace

file:
  dir: C:/repo/dempfrontend/src/assets/

server:
  port: ${PORT:8080}

cloud:
  aws:
    credentials:
      access-key: ${s3.accessKey}
      secret-key: ${s3.secretKey}
    region:
      static: ${s3.static}
    s3:
      bucket: ${s3.bucket}
    stack:
      auto: false