spring:
  profiles:
    active: local
  datasource:
    url: ${clearDB}
    username: ${clearDB_USER}
    password: ${clearDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
#        format_sql: true
#        use_sql_comments: true

  jwt:
    secret: pepega524832857240

#logging.level:
#  org.hibernate.SQL: debug
  # org.hibernate.type: trace

file:
  dir: C:/repo/dempfrontend/src/assets/

server:
  port: 8080