package com.inhatc.demp.domain.announcement;


public enum Language {
    HTML, CSS, React, JAVA, JPA, SPRING,
    KOTLIN, JAVASCRIPT, TYPESCRIPT, PYTHON, GO, C, CPP, CSHARP, RUST, SWIFT, DART, PHP, RUBY, SQL,
    VUE, ANGULAR, NEXT_JS, NUXT_JS, SPRING_BOOT, NODE_JS, NEST_JS, EXPRESS, DJANGO, FASTAPI, DOTNET,
    REACT_NATIVE, FLUTTER, UNITY, UNREAL_ENGINE,
    MYSQL, MARIADB, POSTGRESQL, ORACLE, SQL_SERVER, MONGODB, REDIS, ELASTICSEARCH, KAFKA, RABBITMQ, BIGQUERY,
    AWS, GCP, AZURE, LINUX, DOCKER, KUBERNETES, TERRAFORM, ANSIBLE, PROMETHEUS, GRAFANA,
    PYTORCH, TENSORFLOW, PANDAS, SPARK, AIRFLOW, LANGCHAIN, LLM, RAG, GIT, GITHUB_ACTIONS
}
